name = "license-api"
main = "src/index.ts"
compatibility_date = "2025-09-01"
workers_dev = false
account_id = "9e279d41ad97ded8ad023a9ce9c51b5f"


# ===== PROD (top-level) =====
[[kv_namespaces]]
binding = "LICENSING_KV"
id = "bc5dd377fd5d4b5a8b3f1ac36444136f"
preview_id = "bc5dd377fd5d4b5a8b3f1ac36444136f"

[vars]
TIER = "pro"
CORS_ALLOW_ORIGINS = "http://localhost:5173,app://atropos,https://atropos-video.com"
APP_DOWNLOAD_URL = "https://atropos-video.com/download"
DEEPLINK_SCHEME = "atropos"
SUBSCRIPTION_SUCCESS_URL = "atropos://subscription/complete?result=success"
SUBSCRIPTION_CANCEL_URL = "atropos://subscription/complete?result=cancel"
SUBSCRIPTION_PORTAL_RETURN_URL = "atropos://subscription/manage"
TRANSFER_LINK_TTL_SECONDS = "900"

# ===== DEV env (deploys as license-api-dev) =====
[env.dev]
workers_dev = false

[[env.dev.kv_namespaces]]
binding = "LICENSING_KV"
id = "cf6aca3d77314a4393d0a3532fbcde16"
preview_id = "cf6aca3d77314a4393d0a3532fbcde16"

[env.dev.vars]
TIER = "pro"
CORS_ALLOW_ORIGINS = "http://localhost:5173,app://atropos,https://atropos-video.com"
APP_DOWNLOAD_URL = "https://atropos-video.com/download"
DEEPLINK_SCHEME = "atropos"
SUBSCRIPTION_SUCCESS_URL = "atropos://subscription/complete?result=success"
SUBSCRIPTION_CANCEL_URL = "atropos://subscription/complete?result=cancel"
SUBSCRIPTION_PORTAL_RETURN_URL = "atropos://subscription/manage"
TRANSFER_LINK_TTL_SECONDS = "900"
