name = "licensing-api"
main = "src/index.ts"
compatibility_date = "2024-02-27"
account_id = "9e279d41ad97ded8ad023a9ce9c51b5f"
workers_dev = false

[env.dev]
zone_id = "06ff1a42b61b530829c3877a31a39c7b2"
zone_name = "atropos-video.com"

[[env.dev.routes]]
pattern = "dev.api.atropos-video.com"
custom_domain = true

[env.dev.vars]
TIER = "pro"
CORS_ALLOW_ORIGINS = "http://localhost:5173,http://localhost:3000"

[env.prod]
zone_id = "06ff1a42b61b530829c3877a31a39c7b2"
zone_name = "atropos-video.com"

[[env.prod.routes]]
pattern = "api.atropos-video.com"
custom_domain = true

[env.prod.vars]
TIER = "pro"
CORS_ALLOW_ORIGINS = "https://atropos-video.com"

# KV namespace bindings are populated after Terraform outputs the namespace id.
# Replace the placeholder ids below with the values from Terraform outputs.
[[kv_namespaces]]
binding = "LICENSING_KV"
id = "db363652342e4f28a8e0317a0c2e9de6"
preview_id = "db363652342e4f28a8e0317a0c2e9de6"

[[env.dev.kv_namespaces]]
binding = "LICENSING_KV"
id = "db363652342e4f28a8e0317a0c2e9de6"
preview_id = "db363652342e4f28a8e0317a0c2e9de6"

[[env.prod.kv_namespaces]]
binding = "LICENSING_KV"
id = "72cd84ce754a4dcf95f884bd78f6a83c"
preview_id = "72cd84ce754a4dcf95f884bd78f6a83c"
