"""Configuration constants for clip candidate processing."""

MIN_DURATION_SECONDS = 3.0
MAX_DURATION_SECONDS = 75.0
SWEET_SPOT_MIN_SECONDS = 3.0
SWEET_SPOT_MAX_SECONDS = 25.0

__all__ = [
    "MIN_DURATION_SECONDS",
    "MAX_DURATION_SECONDS",
    "SWEET_SPOT_MIN_SECONDS",
    "SWEET_SPOT_MAX_SECONDS",
]
