"""Configuration constants for clip candidate processing."""

MIN_DURATION_SECONDS = 3.0
MAX_DURATION_SECONDS = 75.0
SWEET_SPOT_MIN_SECONDS = 3.0
SWEET_SPOT_MAX_SECONDS = 25.0

DEFAULT_MIN_RATING = 7.0
DEFAULT_MIN_WORDS = 0

FUNNY_MIN_RATING = 8.0
FUNNY_MIN_WORDS = 5

EDUCATIONAL_MIN_RATING = 7.0
EDUCATIONAL_MIN_WORDS = 8

INSPIRING_MIN_RATING = 7.0
INSPIRING_MIN_WORDS = 8

__all__ = [
    "MIN_DURATION_SECONDS",
    "MAX_DURATION_SECONDS",
    "SWEET_SPOT_MIN_SECONDS",
    "SWEET_SPOT_MAX_SECONDS",
    "DEFAULT_MIN_RATING",
    "DEFAULT_MIN_WORDS",
    "FUNNY_MIN_RATING",
    "FUNNY_MIN_WORDS",
    "EDUCATIONAL_MIN_RATING",
    "EDUCATIONAL_MIN_WORDS",
    "INSPIRING_MIN_RATING",
    "INSPIRING_MIN_WORDS",
]
